### ISSUE TITLE
Can't install on Laravel 7

### ISSUE THREAD

**Issue by JustAnotherCoder133** [drupol/yaroc#5]
## Steps required to reproduce the problem

1. `Type composer require drupol/yaroc`

## Result

Problem 1
    - Root composer.json requires drupol/yaroc ^2.1 -> satisfiable by drupol/yaroc[2.1.0].
    - drupol/yaroc 2.1.0 requires symfony/http-client-contracts ^1 -> found symfony/http-client-contracts[v1.1.1, ..., v1.1.10] but the package is fixed to v2.3.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by drupol** [comment]
Hi !

Do the following:

1. `rm -rf vendor symfony.lock composer.lock`
2. `composer require drupol/yaroc`
3. let me know if it worked.

**Comment by JustAnotherCoder133** [comment]
Nope, same problem.
I can either properly install `symfony/http-client` or `drupol/yaroc`.
If one exists, the other one won't install.

**Comment by drupol** [comment]
Give me a few minutes, going to publish an update.

**Comment by drupol** [comment]
I pushed a few commits on the master branch. Could you please try it? If it's ok, I'll tag a new release.

**Comment by JustAnotherCoder133** [comment]
How do I install the updated version? (Composer still giving same error)

**Comment by drupol** [comment]
> How do I install the updated version?

`composer require drupol/yaroc:dev-master`

If this doesn't work, add this to `composer.json` and try again:

```json
"minimum-stability": "dev",
"prefer-stable": true,

```
> (Composer still giving same error)

Which seems to be normal to me as I didn't tagged anything yet. I'm waiting for your feedback.

**Comment by OP1X3R** [comment]
So I get this error:
[RuntimeException]
  Failed to clone https://github.com/drupol/yaroc.git, git was not found, check that it is installed and in your PATH env.
  sh: 1: git: not found

**Comment by drupol** [comment]
You should install `git` :)

**Comment by JustAnotherCoder133** [comment]
Well, I just tried your example and it printed me the correct result, so I guess it works ^.^

**Comment by drupol** [comment]
Excellent ! Tagging 2.2.0 !

**Comment by drupol** [comment]
Release 2.2.0 has been tagged and pushed, you may now use it :)

`composer require drupol/yaroc:^2.2`
